-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet

-- customized because Im using terminal version of nvim
-- on an unsupported terminal.
-- note: st is supported with a patch, so may return to st
return {
  kind = {
    Text = " ",
    Method = " ",
    Function = " ",
    Constructor = " ",
    Field = " ",
    Variable = " ",
    Class = " ",
    Interface = " ",
    Module = " ",
    Property = " ",
    Unit = " ",
    Value = " ",
    Enum = " ",
    Keyword = "🔑 ",
    Snippet = " ",
    Color = " ",
    File = " ",
    Reference = " ",
    Folder = " ",
    EnumMember = " ",
    Constant = "K ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
    Misc = " ",
  },
  type = {
    Array = " ",
    Number = "💯 ",
    String = " ",
    Boolean = " ",
    Object = " ",
  },
  documents = {
    File = "📄 ",
    Files = "📃 ", 
    Folder = "📁 ",
    OpenFolder = "📂 ",
  },
  git = {
    Add = " ",
    Mod = " ",
    Remove = " ",
    Ignore = " ",
    Rename = " ",
    Diff = " ",
    Repo = " ",
  },
  ui = {
    Lock = " ",
    Circle = " ",
    BigCircle = " ",
    BigUnfilledCircle = " ",
    Close = " ",
    NewFile = " ",
    Search = " ",
    Lightbulb = " ",
    Project = " ",
    Dashboard = " ",
    History = " ",
    Comment = " ",
    Bug = " ",
    Code = " ",
    Telescope = " ",
    Gear = " ",
    Package = " ",
    List = " ",
    SignIn = " ",
    Check = " ",
    Fire = " ",
    Note = " ",
    BookMark = " ",
    Pencil = " ",
    ChevronRight = "",
    Table = " ",
    Calendar = " ",
  },
  diagnostics = { 
    Error = " ⁉️",
    Warning = "⚠️",
    Information = " ",
    Question = "❓",
    Hint = " ",
  },
  misc = {
    Robot = "🤖",
    Squirrel = "🦑",
    Tag = "<>",
    Watch = " ",
  },
}

-- the original return set 
--   פּ ﯟ   蘒練 some other good icons
-- return {
--   kind = {
--     Text = " ",
--     Method = " ",
--     Function = " ",
--     Constructor = " ",
--     Field = " ",
--     Variable = " ",
--     Class = " ",
--     Interface = " ",
--     Module = " ",
--     Property = " ",
--     Unit = " ",
--     Value = " ",
--     Enum = " ",
--     Keyword = " ",
--     Snippet = " ",
--     Color = " ",
--     File = " ",
--     Reference = " ",
--     Folder = " ",
--     EnumMember = " ",
--     Constant = " ",
--     Struct = " ",
--     Event = " ",
--     Operator = " ",
--     TypeParameter = " ",
--     Misc = " ",
--   },
--   type = {
--     Array = " ",
--     Number = " ",
--     String = " ",
--     Boolean = " ",
--     Object = " ",
--   },
--   documents = {
--     File = " ",
--     Files = " ",
--     Folder = " ",
--     OpenFolder = " ",
--   },
--   git = {
--     Add = " ",
--     Mod = " ",
--     Remove = " ",
--     Ignore = " ",
--     Rename = " ",
--     Diff = " ",
--     Repo = " ",
--   },
--   ui = {
--     Lock = " ",
--     Circle = " ",
--     BigCircle = " ",
--     BigUnfilledCircle = " ",
--     Close = " ",
--     NewFile = " ",
--     Search = " ",
--     Lightbulb = " ",
--     Project = " ",
--     Dashboard = " ",
--     History = " ",
--     Comment = " ",
--     Bug = " ",
--     Code = " ",
--     Telescope = " ",
--     Gear = " ",
--     Package = " ",
--     List = " ",
--     SignIn = " ",
--     Check = " ",
--     Fire = " ",
--     Note = " ",
--     BookMark = " ",
--     Pencil = " ",
--     ChevronRight = "",
--     Table = " ",
--     Calendar = " ",
--   },
--   diagnostics = {
--     Error = " ",
--     Warning = " ",
--     Information = " ",
--     Question = " ",
--     Hint = " ",
--   },
--   misc = {
--     Robot = " ",
--     Squirrel = " ",
--     Tag = " ",
--     Watch = " ",
--   },
-- }
